### ISSUE TITLE
Error with time.sleep()

### ISSUE THREAD

**Issue by billsargent** [E-Krabs/rule34-tag-counter#1]
Here's what I get when I run your code. 

Traceback (most recent call last):
  File "/home/pi/rule34-tag-counter/fetchall.py", line 81, in <module>
    time.sleep(1-(time.time()-s))
ValueError: sleep length must be non-negative

**Comment by E-Krabs** [comment]
Sorry this repo has been neglected for awhile. For now just replace that line with <code>time.sleep(1.5)</code>. We do this to avoid their server blocking us for overusage. However, there are much better ways of retrieving these, and I've been updating them for my e621 repo, where we actually download a csv with everything in it, no need for fetching which usually took around five hours. I will implement this new system when I return home later today.

**Comment by billsargent** [comment]
Do you have one for rule34.paheal.net as well? 

Yeah I had modified it to put a 2 second delay in.  :) Thanks

**Comment by E-Krabs** [comment]
I can surly update this one to encompass that site as well, as long as they have normal api access. Sometimes, they like to lock things down for some reason. At the moment, there are no analysis scripts in this repository as well, I will port my e621 ones to here in a few like graphs and stuff.

**Comment by E-Krabs** [comment]
Unfortunately, paheal doesn't have any csv to download. That would be ok, but nor do they have an exposed endpoint for posts, only the html main page (they do however have one for tag counts). This means I'd have to scrape the html page to retrieve the post's url, and then scrape the post's page for it's tags and stuff. That is easily possible but will most likely be slow cause it'd have to make tonnes of requests. On top of the requests, it'd need to sleep to avoid overloading their server. Their documentation [https://shimmie.shishnet.org/doc/] doesn't even work. For now, Ill be porting the analysis scripts and updating the fetcher. Ill try to find a more efficient way of scraping paheal. Thanks for your interest
